// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/nicdoye/quaytermass/client/billing"
	"github.com/nicdoye/quaytermass/client/build"
	"github.com/nicdoye/quaytermass/client/discovery"
	"github.com/nicdoye/quaytermass/client/error"
	"github.com/nicdoye/quaytermass/client/image"
	"github.com/nicdoye/quaytermass/client/logs"
	"github.com/nicdoye/quaytermass/client/organization"
	"github.com/nicdoye/quaytermass/client/permission"
	"github.com/nicdoye/quaytermass/client/prototype"
	"github.com/nicdoye/quaytermass/client/repository"
	"github.com/nicdoye/quaytermass/client/repositorynotification"
	"github.com/nicdoye/quaytermass/client/repotoken"
	"github.com/nicdoye/quaytermass/client/robot"
	"github.com/nicdoye/quaytermass/client/search"
	"github.com/nicdoye/quaytermass/client/secscan"
	"github.com/nicdoye/quaytermass/client/tag"
	"github.com/nicdoye/quaytermass/client/team"
	"github.com/nicdoye/quaytermass/client/trigger"
	"github.com/nicdoye/quaytermass/client/user"
)

// Default quay frontend HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "quay.io"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new quay frontend HTTP client.
func NewHTTPClient(formats strfmt.Registry) *QuayFrontend {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new quay frontend HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *QuayFrontend {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new quay frontend client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *QuayFrontend {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(QuayFrontend)
	cli.Transport = transport

	cli.Billing = billing.New(transport, formats)

	cli.Build = build.New(transport, formats)

	cli.Discovery = discovery.New(transport, formats)

	cli.Error = error.New(transport, formats)

	cli.Image = image.New(transport, formats)

	cli.Logs = logs.New(transport, formats)

	cli.Organization = organization.New(transport, formats)

	cli.Permission = permission.New(transport, formats)

	cli.Prototype = prototype.New(transport, formats)

	cli.Repository = repository.New(transport, formats)

	cli.Repositorynotification = repositorynotification.New(transport, formats)

	cli.Repotoken = repotoken.New(transport, formats)

	cli.Robot = robot.New(transport, formats)

	cli.Search = search.New(transport, formats)

	cli.Secscan = secscan.New(transport, formats)

	cli.Tag = tag.New(transport, formats)

	cli.Team = team.New(transport, formats)

	cli.Trigger = trigger.New(transport, formats)

	cli.User = user.New(transport, formats)

	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// QuayFrontend is a client for quay frontend
type QuayFrontend struct {
	Billing *billing.Client

	Build *build.Client

	Discovery *discovery.Client

	Error *error.Client

	Image *image.Client

	Logs *logs.Client

	Organization *organization.Client

	Permission *permission.Client

	Prototype *prototype.Client

	Repository *repository.Client

	Repositorynotification *repositorynotification.Client

	Repotoken *repotoken.Client

	Robot *robot.Client

	Search *search.Client

	Secscan *secscan.Client

	Tag *tag.Client

	Team *team.Client

	Trigger *trigger.Client

	User *user.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *QuayFrontend) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.Billing.SetTransport(transport)

	c.Build.SetTransport(transport)

	c.Discovery.SetTransport(transport)

	c.Error.SetTransport(transport)

	c.Image.SetTransport(transport)

	c.Logs.SetTransport(transport)

	c.Organization.SetTransport(transport)

	c.Permission.SetTransport(transport)

	c.Prototype.SetTransport(transport)

	c.Repository.SetTransport(transport)

	c.Repositorynotification.SetTransport(transport)

	c.Repotoken.SetTransport(transport)

	c.Robot.SetTransport(transport)

	c.Search.SetTransport(transport)

	c.Secscan.SetTransport(transport)

	c.Tag.SetTransport(transport)

	c.Team.SetTransport(transport)

	c.Trigger.SetTransport(transport)

	c.User.SetTransport(transport)

}
