// Code generated by go-swagger; DO NOT EDIT.

package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/nicdoye/quaytermass/models"
)

// NewChangeTagImageParams creates a new ChangeTagImageParams object
// with the default values initialized.
func NewChangeTagImageParams() *ChangeTagImageParams {
	var ()
	return &ChangeTagImageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewChangeTagImageParamsWithTimeout creates a new ChangeTagImageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewChangeTagImageParamsWithTimeout(timeout time.Duration) *ChangeTagImageParams {
	var ()
	return &ChangeTagImageParams{

		timeout: timeout,
	}
}

// NewChangeTagImageParamsWithContext creates a new ChangeTagImageParams object
// with the default values initialized, and the ability to set a context for a request
func NewChangeTagImageParamsWithContext(ctx context.Context) *ChangeTagImageParams {
	var ()
	return &ChangeTagImageParams{

		Context: ctx,
	}
}

// NewChangeTagImageParamsWithHTTPClient creates a new ChangeTagImageParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewChangeTagImageParamsWithHTTPClient(client *http.Client) *ChangeTagImageParams {
	var ()
	return &ChangeTagImageParams{
		HTTPClient: client,
	}
}

/*ChangeTagImageParams contains all the parameters to send to the API endpoint
for the change tag image operation typically these are written to a http.Request
*/
type ChangeTagImageParams struct {

	/*Body
	  Request body contents.

	*/
	Body *models.MoveTag
	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string
	/*Tag
	  The name of the tag

	*/
	Tag string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the change tag image params
func (o *ChangeTagImageParams) WithTimeout(timeout time.Duration) *ChangeTagImageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the change tag image params
func (o *ChangeTagImageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the change tag image params
func (o *ChangeTagImageParams) WithContext(ctx context.Context) *ChangeTagImageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the change tag image params
func (o *ChangeTagImageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the change tag image params
func (o *ChangeTagImageParams) WithHTTPClient(client *http.Client) *ChangeTagImageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the change tag image params
func (o *ChangeTagImageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the change tag image params
func (o *ChangeTagImageParams) WithBody(body *models.MoveTag) *ChangeTagImageParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the change tag image params
func (o *ChangeTagImageParams) SetBody(body *models.MoveTag) {
	o.Body = body
}

// WithRepository adds the repository to the change tag image params
func (o *ChangeTagImageParams) WithRepository(repository string) *ChangeTagImageParams {
	o.SetRepository(repository)
	return o
}

// SetRepository adds the repository to the change tag image params
func (o *ChangeTagImageParams) SetRepository(repository string) {
	o.Repository = repository
}

// WithTag adds the tag to the change tag image params
func (o *ChangeTagImageParams) WithTag(tag string) *ChangeTagImageParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the change tag image params
func (o *ChangeTagImageParams) SetTag(tag string) {
	o.Tag = tag
}

// WriteToRequest writes these params to a swagger request
func (o *ChangeTagImageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	// path param tag
	if err := r.SetPathParam("tag", o.Tag); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
